# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  roots-example-project.com:
    site_hosts:
      - roots-example-project.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:roots/roots-example-project.com.git # replace with your Git repo URL
    branch: master
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: https://roots-example-project.com
      wp_siteurl: https://roots-example-project.com/wp
      wp_env: production
      db_name: roots_example_project_prod
      db_user: roots_example_project_prod
      # Define the following variables in group_vars/production/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
